#!/usr/bin/env bash
# Install Monitor Align for the current user (no root, idempotent).
#
#   ./install.sh          install the KWin script via kpackagetool6, copy the daemon and the unit
#   ./install.sh --link   symlink into this repository instead of copying (development)
#   ./install.sh --uninstall
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_ID=monitoralign
PKG_DIR="$HOME/.local/share/kwin/scripts/$PKG_ID"
BIN="$HOME/.local/bin/monitoralign-daemon"
UNIT="$HOME/.config/systemd/user/monitoralign.service"

ok()   { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
info() { printf '\033[1;34m::\033[0m %s\n' "$*"; }

# The settings page (config.ui / main.xml) is generated by the daemon; seed a placeholder until then.
seed_templates() {
  mkdir -p "$PKG_DIR/contents/config" "$PKG_DIR/contents/ui"
  [ -e "$PKG_DIR/contents/config/main.xml" ] || cp "$HERE/templates/main.xml" "$PKG_DIR/contents/config/main.xml"
  [ -e "$PKG_DIR/contents/ui/config.ui" ]    || cp "$HERE/templates/config.ui" "$PKG_DIR/contents/ui/config.ui"
}

uninstall() {
  systemctl --user disable --now monitoralign.service 2>/dev/null || true
  rm -f "$UNIT" "$BIN"
  if [ -L "$PKG_DIR" ]; then rm -f "$PKG_DIR"; else kpackagetool6 -t KWin/Script -r "$PKG_ID" 2>/dev/null || rm -rf "$PKG_DIR"; fi
  kwriteconfig6 --file kwinrc --group Plugins --key "${PKG_ID}Enabled" --delete 2>/dev/null || true
  systemctl --user daemon-reload
  ok "Monitor Align uninstalled ([Script-monitoralign] in kwinrc was left in place)"
}

case "${1:-}" in
  --uninstall) uninstall; exit 0 ;;
  --link) LINK=1 ;;
  "") LINK=0 ;;
  *) echo "usage: $0 [--link|--uninstall]" >&2; exit 2 ;;
esac

for c in kpackagetool6 kscreen-doctor kreadconfig6 kwriteconfig6 python3; do
  command -v "$c" >/dev/null || { echo "missing command: $c" >&2; exit 1; }
done
python3 -c 'import PySide6.QtCore' 2>/dev/null || { echo "PySide6 for Python 3 is required (Fedora: dnf install python3-pyside6; Arch: pyside6; Debian/Ubuntu: python3-pyside6.qtcore)" >&2; exit 1; }

mkdir -p "$(dirname "$BIN")" "$(dirname "$UNIT")" "$(dirname "$PKG_DIR")"
if [ "$LINK" = 1 ]; then
  [ -d "$PKG_DIR" ] && [ ! -L "$PKG_DIR" ] && kpackagetool6 -t KWin/Script -r "$PKG_ID" >/dev/null 2>&1 || true
  ln -sfn "$HERE/package" "$PKG_DIR"
  ln -sf "$HERE/package/contents/bin/monitoralign-daemon" "$BIN"
  ln -sf "$HERE/package/contents/systemd/monitoralign.service" "$UNIT"
  ok "symlinked: $PKG_DIR, $BIN, $UNIT"
  seed_templates
else
  if [ -L "$PKG_DIR" ]; then rm -f "$PKG_DIR"; fi
  if [ -d "$PKG_DIR" ]; then kpackagetool6 -t KWin/Script -u "$HERE/package" >/dev/null; else kpackagetool6 -t KWin/Script -i "$HERE/package" >/dev/null; fi
  install -m 0755 "$HERE/package/contents/bin/monitoralign-daemon" "$BIN"
  install -m 0644 "$HERE/package/contents/systemd/monitoralign.service" "$UNIT"
  seed_templates
  ok "installed: $PKG_DIR, $BIN, $UNIT"
fi

kwriteconfig6 --file kwinrc --group Plugins --key "${PKG_ID}Enabled" true
systemctl --user daemon-reload
systemctl --user enable --now monitoralign.service
sleep 1
info "Settings page: System Settings > Window Management > KWin Scripts > Monitor Align (gear icon)"
"$BIN" --status
